name = "Quick Reaction Force Spawner"
prefix = "qrfs"
mainprefix = "z"
author = "CryptikLemur"

[version]
path = "addons/main/script_version.hpp"

[files]
include = ["mod.cpp", "logo.paa", "logo_small.paa"]
exclude = ["bin/*", "RawAssets/*"]

[hemtt.release]
sign = false
